export const paths = {
  home: '/',
  dashboard: '/dashboard',
  partners: '/partner-currency/partners',
  games: '/games',
  currencygames: '/currencygames',
  sessionsForGameCurrency: '/currencygames/sessions-for-gamecurrency',
  searchplayer: '/searchplayer',
  players: '/partner/partners-currency/players',
  sessions2: '/partner/partners-currency/sessions2',
  sessionEvents: '/partner/partners-currency/players/sessions',
  login: '/login',
  partnerCurrency: '/partner-currency',
  searchplayer_2: '/searchplayer-2',
};
